<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SISGEDI | Revisión de Evidencias</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="{{ asset('libs/Fontawesome6/css/fontawesome.css') }}" rel="stylesheet">
    <link href="{{ asset('libs/Fontawesome6/css/solid.css') }}" rel="stylesheet">
    <link href="{{ route('sisgedi.assets.gestor_css') }}" rel="stylesheet">
</head>
<body class="gestor-shell">
    <aside class="gestor-sidebar"><div class="brand-block"><div class="brand-mark">SG</div><div><strong>SISGEDI</strong><span>Gestión Integral</span></div></div><nav class="gestor-nav"><p class="nav-label">General</p><a class="nav-item" href="{{ route($esLider ? 'sisgedi.dashboard.lider' : 'sisgedi.dashboard.gestor') }}"><i class="fa-solid fa-grid-2"></i><span>Dashboard Principal</span></a><p class="nav-label">Tareas y Cascada</p><a class="nav-item" href="{{ route('sisgedi.tareas_recibidas') }}"><i class="fa-solid fa-layer-group"></i><span>Tareas Recibidas</span></a>@if ($esLider)<a class="nav-item" href="{{ route('sisgedi.lider.tareas_colaboradores') }}"><i class="fa-solid fa-clipboard-list"></i><span>Tareas para Colaboradores</span></a>@else<a class="nav-item" href="{{ route('sisgedi.gestor.tareas_lideres') }}"><i class="fa-solid fa-clipboard-list"></i><span>Tareas para Líderes</span></a>@endif<p class="nav-label">Evidencias</p><a class="nav-item" href="{{ route('sisgedi.lider.mis_evidencias') }}"><i class="fa-solid fa-upload"></i><span>Mis Evidencias</span></a><a class="nav-item is-active" href="{{ route('sisgedi.gestor.revision_evidencias') }}"><i class="fa-solid fa-file-circle-check"></i><span>Revisión de Evidencias</span></a><button class="nav-item nav-disabled" type="button" disabled><i class="fa-solid fa-file-lines"></i><span>Listado Maestro</span><small>Próximamente</small></button><p class="nav-label">Seguimiento</p><button class="nav-item nav-disabled" type="button" disabled><i class="fa-solid fa-book-open"></i><span>{{ $esLider ? 'Bitácoras del Equipo' : 'Bitácoras del Sector' }}</span><small>Próximamente</small></button><button class="nav-item nav-disabled" type="button" disabled><i class="fa-solid fa-calendar-days"></i><span>Cronograma</span><small>Próximamente</small></button></nav><div class="location-card"><strong>Centro La Angostura</strong><span>Campoalegre, Huila</span></div></aside>
    <div class="gestor-main"><header class="gestor-topbar"><button class="menu-toggle" type="button"><i class="fa-solid fa-bars"></i></button><div class="topbar-actions"><div class="notification-button has-notifications"><span class="notification-symbol">!</span><b>{{ $notificationCount }}</b></div><div class="profile-block"><div class="profile-avatar">{{ strtoupper(substr($user['nombre'], 0, 2)) }}</div><div class="profile-details"><strong>{{ $user['nombre'] }}</strong><span>{{ $esLider ? 'Líder' : 'Gestor' }}</span></div><form action="{{ route('sisgedi.logout') }}" method="POST" class="leader-logout">@csrf<button type="submit" aria-label="Cerrar sesión"><i class="fa-solid fa-right-from-bracket"></i></button></form></div></div></header>
        <main class="gestor-content"><div class="breadcrumb">Inicio</div><div class="page-heading"><div><h1>Revisión de Evidencias</h1><p>{{ $subtitle }}</p></div><span class="area-badge">{{ $area }}</span></div><section class="review-grid"><article class="review-card"><div class="review-card-title"><i class="fa-regular fa-file-lines"></i><strong>Evidencia seleccionada — {{ $selectedEvidence->codigo ?? 'Sin evidencias' }}</strong></div>@if ($selectedEvidence)<p class="review-meta">{{ $selectedEvidence->usuario_nombre }} · {{ $esLider ? 'Colaborador' : 'Líder' }} — Tarea: {{ $selectedEvidence->titulo }}</p><div class="evidence-preview"><a href="{{ route('sisgedi.evidencia.show', $selectedEvidence->evidencia_id) }}"><i class="fa-solid fa-file-lines"></i><span>{{ basename($selectedEvidence->archivo) }}</span><small>Ver documento en solo lectura</small></a></div><h3>HISTORIAL DE VERSIONES</h3><div class="history-item"><b>v{{ $selectedEvidence->version }}</b><span>Cargada — {{ ucfirst(str_replace('_', ' ', $selectedEvidence->estado)) }}<small>{{ optional($selectedEvidence->created_at)->format('d M Y, H:i') }}</small></span></div><form class="review-decision" method="POST" action="{{ route('sisgedi.gestor.revision_evidencias.rechazar') }}">@csrf<input type="hidden" name="evidencia_id" value="{{ $selectedEvidence->evidencia_id }}"><label>MOTIVO DE RECHAZO (OBLIGATORIO SI SE RECHAZA)<textarea name="motivo_rechazo" placeholder="Escribe el motivo del rechazo..."></textarea></label><div><button class="review-approve" type="submit" formaction="{{ route('sisgedi.gestor.revision_evidencias.aprobar') }}"><i class="fa-solid fa-check"></i> Aprobar evidencia</button><button class="review-reject" type="submit"><i class="fa-solid fa-xmark"></i> Rechazar con motivo</button></div></form>@else<div class="module-empty"><i class="fa-solid fa-inbox"></i><strong>No hay evidencias pendientes</strong></div>@endif</article><aside class="pending-card"><h2>Pendientes por revisar ({{ $items->count() }})</h2>@foreach ($items as $evidence)<a class="pending-item" href="{{ route('sisgedi.gestor.revision_evidencias') }}"><span class="pending-icon"><i class="fa-solid fa-file-lines"></i></span><div><strong>{{ $evidence->codigo }} — {{ $evidence->usuario_nombre }}</strong><small>{{ $evidence->titulo }}</small></div><em>En revisión</em></a>@endforeach</aside></section></main></div>
</body>
</html>
